development:
  adapter:   postgresql
  database:  my_e_commerce_development
  username:  postgres
  password:  123
  host:      localhost
  port:      5432
test:
  adapter:   postgresql
  database:  my_e_commerce_test
  username:  postgres
  password:  123
  host:      localhost
  port:      5432
